"""Seed the database with London/Europe-focused demo data."""
import json
import random
from datetime import datetime, timedelta
from backend.database import init_db, get_db, upsert_company, bulk_insert_jobs
from backend.scorer import score_all_companies

DEMO_COMPANIES = [
    # === US COMPANIES OPENING LONDON OFFICES ===
    {
        "name": "Stripe",
        "domain": "stripe.com",
        "industry": "Financial Infrastructure",
        "hq_city": "London",
        "hq_state": "England",
        "hq_country": "UK",
        "submarket": "King's Cross / Pancras Square",
        "employee_count": 8000,
        "founded_year": 2010,
        "funding_total_usd": 8700000000,
        "latest_funding_round": "Series I",
        "latest_funding_date": "2025-06-15",
        "latest_funding_amount": 6500000000,
        "revenue_range": "$1B+",
        "glassdoor_rating": 3.8,
        "hybrid_percentage": 60,
        "linkedin_url": "https://linkedin.com/company/stripe",
        "crunchbase_url": "https://crunchbase.com/organization/stripe",
        "website": "https://stripe.com",
        "description": "Stripe is the financial infrastructure platform used by millions of companies. Doubling its London engineering hub as its EMEA HQ ahead of IPO.",
        "contact_name": "Matt Henderson",
        "contact_title": "Head of UK & Ireland",
        "contact_email": "m.henderson@stripe.com",
        "contact_phone": "+44 20 7946 0101",
        "signal_tags": json.dumps(["London Expansion", "Pre-IPO", "EMEA HQ"]),
        "ai_summary": "Doubling London headcount to 400+ as EMEA HQ. Actively scouting 40K SF in King's Cross and Shoreditch.",
        "ai_description": "Stripe is making London its EMEA headquarters ahead of a 2026 IPO. They're outgrowing their current Pancras Square space and need 40K+ SF of Class A office to house engineering, sales, and compliance teams. Budget is not a constraint given $6.5B in recent funding.",
        "hiring_trend": json.dumps([
            {"month": "Oct", "count": 18}, {"month": "Nov", "count": 24},
            {"month": "Dec", "count": 30}, {"month": "Jan", "count": 38},
            {"month": "Feb", "count": 45}, {"month": "Mar", "count": 55}
        ]),
        "evidence": json.dumps([
            {"date": "2025-06-15", "event": "Funding", "description": "Raised $6.5B at $65B valuation for liquidity ahead of IPO."},
            {"date": "2026-01-20", "event": "London Expansion", "description": "Announced plan to double London engineering team to 400+."},
            {"date": "2026-03-10", "event": "Real Estate", "description": "Engaged Cushman & Wakefield for 40K SF search in King's Cross / Shoreditch."},
        ]),
    },
    {
        "name": "Scale AI",
        "domain": "scale.com",
        "industry": "Artificial Intelligence",
        "hq_city": "London",
        "hq_state": "England",
        "hq_country": "UK",
        "submarket": "Soho / Fitzrovia",
        "employee_count": 1200,
        "founded_year": 2016,
        "funding_total_usd": 1600000000,
        "latest_funding_round": "Series F",
        "latest_funding_date": "2025-05-20",
        "latest_funding_amount": 1000000000,
        "revenue_range": "$200M-$500M",
        "glassdoor_rating": 3.6,
        "hybrid_percentage": 70,
        "linkedin_url": "https://linkedin.com/company/scaleai",
        "crunchbase_url": "https://crunchbase.com/organization/scale-ai",
        "website": "https://scale.com",
        "description": "Scale AI accelerates AI development with training data and enterprise solutions. Opening first London office to serve UK government and defence contracts.",
        "contact_name": "Victoria Sheridan",
        "contact_title": "VP EMEA",
        "contact_email": "v.sheridan@scale.com",
        "contact_phone": "+44 20 7946 0102",
        "signal_tags": json.dumps(["New London Office", "Government Contracts", "Series F Funded"]),
        "ai_summary": "Opening first UK office for MOD and GCHQ contracts. Seeking 10K SF secure workspace in central London.",
        "ai_description": "Scale AI is entering the UK market to serve Ministry of Defence and intelligence community data labeling contracts. They need secure, OFFICIAL-SENSITIVE compliant office space in central London, preferably near Whitehall or the City.",
        "hiring_trend": json.dumps([
            {"month": "Oct", "count": 5}, {"month": "Nov", "count": 8},
            {"month": "Dec", "count": 12}, {"month": "Jan", "count": 18},
            {"month": "Feb", "count": 24}, {"month": "Mar", "count": 30}
        ]),
        "evidence": json.dumps([
            {"date": "2025-05-20", "event": "Funding", "description": "Raised $1B Series F at $14B valuation."},
            {"date": "2026-02-01", "event": "UK Entry", "description": "Announced UK subsidiary Scale AI Ltd, registered at Companies House."},
            {"date": "2026-03-15", "event": "Hiring", "description": "15 London-based roles posted: defence, engineering, sales."},
        ]),
    },
    {
        "name": "Databricks",
        "domain": "databricks.com",
        "industry": "Data & Analytics",
        "hq_city": "London",
        "hq_state": "England",
        "hq_country": "UK",
        "submarket": "Paddington / Marylebone",
        "employee_count": 7000,
        "founded_year": 2013,
        "funding_total_usd": 4600000000,
        "latest_funding_round": "Series J",
        "latest_funding_date": "2025-12-01",
        "latest_funding_amount": 10000000000,
        "revenue_range": "$1B+",
        "glassdoor_rating": 4.0,
        "hybrid_percentage": 70,
        "linkedin_url": "https://linkedin.com/company/databricks",
        "crunchbase_url": "https://crunchbase.com/organization/databricks",
        "website": "https://databricks.com",
        "description": "Databricks is the data and AI company. Tripling its London office as part of aggressive EMEA expansion pre-IPO.",
        "contact_name": "Jonathan Hart",
        "contact_title": "VP Northern Europe",
        "contact_email": "j.hart@databricks.com",
        "contact_phone": "+44 20 7946 0103",
        "signal_tags": json.dumps(["Mega Round", "London Tripling", "Pre-IPO"]),
        "ai_summary": "Tripling London office from 80 to 250+ staff. Moving from WeWork to dedicated 30K SF campus in Paddington.",
        "ai_description": "Databricks is consolidating from three WeWork floors into a single dedicated campus in London. With $10B in funding and IPO preparation, they're seeking premium 30K SF space near Paddington or King's Cross to house their growing UK engineering and sales organisation.",
        "hiring_trend": json.dumps([
            {"month": "Oct", "count": 20}, {"month": "Nov", "count": 28},
            {"month": "Dec", "count": 35}, {"month": "Jan", "count": 42},
            {"month": "Feb", "count": 50}, {"month": "Mar", "count": 60}
        ]),
        "evidence": json.dumps([
            {"date": "2025-12-01", "event": "Funding", "description": "Raised $10B at $62B valuation, largest private round ever."},
            {"date": "2026-01-15", "event": "London Growth", "description": "UK MD announced plan to triple London headcount to 250+."},
            {"date": "2026-03-05", "event": "Real Estate", "description": "Touring 25-35K SF options in Paddington and King's Cross."},
        ]),
    },
    {
        "name": "Ramp",
        "domain": "ramp.com",
        "industry": "FinTech",
        "hq_city": "London",
        "hq_state": "England",
        "hq_country": "UK",
        "submarket": "City of London / Moorgate",
        "employee_count": 900,
        "founded_year": 2019,
        "funding_total_usd": 1600000000,
        "latest_funding_round": "Series D",
        "latest_funding_date": "2025-09-15",
        "latest_funding_amount": 300000000,
        "revenue_range": "$100M-$200M",
        "glassdoor_rating": 4.2,
        "hybrid_percentage": 80,
        "linkedin_url": "https://linkedin.com/company/ramp-financial",
        "crunchbase_url": "https://crunchbase.com/organization/ramp-financial",
        "website": "https://ramp.com",
        "description": "Ramp is the corporate card and spend management platform. Launching UK operations with a London office to compete with Pleo and Spendesk.",
        "contact_name": "James Whitworth",
        "contact_title": "GM United Kingdom",
        "contact_email": "j.whitworth@ramp.com",
        "contact_phone": "+44 20 7946 0104",
        "signal_tags": json.dumps(["New London Office", "Series D Funded", "UK Launch"]),
        "ai_summary": "Launching UK operations from London. Seeking 8K SF in the City for 50-person team by Q3 2026.",
        "ai_description": "Ramp is entering the UK corporate card market to compete with Pleo and Spendesk. They're hiring a London-based GM and initial team of 50 covering sales, compliance, and engineering. Need FCA-compliant office space near the City or Canary Wharf.",
        "hiring_trend": json.dumps([
            {"month": "Oct", "count": 2}, {"month": "Nov", "count": 5},
            {"month": "Dec", "count": 8}, {"month": "Jan", "count": 14},
            {"month": "Feb", "count": 20}, {"month": "Mar", "count": 28}
        ]),
        "evidence": json.dumps([
            {"date": "2025-09-15", "event": "Funding", "description": "Closed $300M Series D at $7.65B valuation."},
            {"date": "2026-01-10", "event": "UK Launch", "description": "Applied for FCA e-money institution licence."},
            {"date": "2026-03-20", "event": "Hiring", "description": "28 London roles posted: GM, compliance, sales, engineering."},
        ]),
    },
    {
        "name": "Wiz",
        "domain": "wiz.io",
        "industry": "Cybersecurity",
        "hq_city": "London",
        "hq_state": "England",
        "hq_country": "UK",
        "submarket": "Shoreditch / Old Street",
        "employee_count": 1800,
        "founded_year": 2020,
        "funding_total_usd": 1900000000,
        "latest_funding_round": "Series E",
        "latest_funding_date": "2025-05-10",
        "latest_funding_amount": 1000000000,
        "revenue_range": "$500M-$1B",
        "glassdoor_rating": 4.3,
        "hybrid_percentage": 65,
        "linkedin_url": "https://linkedin.com/company/wizsecurity",
        "crunchbase_url": "https://crunchbase.com/organization/wiz-inc",
        "website": "https://wiz.io",
        "description": "Wiz provides cloud security for the modern enterprise. Expanding London office as EMEA sales hub.",
        "contact_name": "Daniel Cohen",
        "contact_title": "VP EMEA Sales",
        "contact_email": "d.cohen@wiz.io",
        "contact_phone": "+44 20 7946 0105",
        "signal_tags": json.dumps(["Rapid Growth", "London Expansion", "Series E Funded"]),
        "ai_summary": "Fastest-growing cybersecurity company expanding London from 30 to 120+ as EMEA sales hub.",
        "ai_description": "Wiz is quadrupling its London team to serve the rapidly growing UK and European enterprise cloud security market. Current Shoreditch office is at capacity; they need 15K+ SF for a dedicated EMEA sales and customer success centre.",
        "hiring_trend": json.dumps([
            {"month": "Oct", "count": 10}, {"month": "Nov", "count": 15},
            {"month": "Dec", "count": 22}, {"month": "Jan", "count": 30},
            {"month": "Feb", "count": 38}, {"month": "Mar", "count": 45}
        ]),
        "evidence": json.dumps([
            {"date": "2025-05-10", "event": "Funding", "description": "Closed $1B Series E at $12B valuation."},
            {"date": "2026-01-20", "event": "London Growth", "description": "EMEA VP announced 4x London headcount target."},
            {"date": "2026-03-12", "event": "Real Estate", "description": "Outgrown current 3K SF Shoreditch space; touring 15K+ options."},
        ]),
    },
    {
        "name": "CoreWeave",
        "domain": "coreweave.com",
        "industry": "Cloud Computing",
        "hq_city": "London",
        "hq_state": "England",
        "hq_country": "UK",
        "submarket": "Canary Wharf / Docklands",
        "employee_count": 1600,
        "founded_year": 2017,
        "funding_total_usd": 12100000000,
        "latest_funding_round": "Series C",
        "latest_funding_date": "2025-11-01",
        "latest_funding_amount": 7500000000,
        "revenue_range": "$500M-$1B",
        "glassdoor_rating": 3.5,
        "hybrid_percentage": 55,
        "linkedin_url": "https://linkedin.com/company/coreweave",
        "crunchbase_url": "https://crunchbase.com/organization/coreweave",
        "website": "https://coreweave.com",
        "description": "CoreWeave is a GPU cloud provider for AI workloads. Opening London office alongside new UK data centres.",
        "contact_name": "Sarah Pennington",
        "contact_title": "UK Country Manager",
        "contact_email": "s.pennington@coreweave.com",
        "contact_phone": "+44 20 7946 0106",
        "signal_tags": json.dumps(["Mega Funding", "New London Office", "Data Centres"]),
        "ai_summary": "$7.5B-funded GPU cloud opening London office alongside UK data centre build-out. 20K SF needed.",
        "ai_description": "CoreWeave is building GPU data centres in the UK and needs a London corporate office for sales, partnerships, and infrastructure operations. Seeking 15-20K SF near Canary Wharf or the City with excellent connectivity.",
        "hiring_trend": json.dumps([
            {"month": "Oct", "count": 3}, {"month": "Nov", "count": 8},
            {"month": "Dec", "count": 15}, {"month": "Jan", "count": 22},
            {"month": "Feb", "count": 30}, {"month": "Mar", "count": 40}
        ]),
        "evidence": json.dumps([
            {"date": "2025-11-01", "event": "Funding", "description": "Closed $7.5B Series C, largest AI infra round."},
            {"date": "2026-01-15", "event": "UK Entry", "description": "Announced two UK data centres in Slough and Manchester."},
            {"date": "2026-03-08", "event": "Hiring", "description": "40 UK roles posted: data centre ops, sales, engineering."},
        ]),
    },
    # === LONDON-NATIVE / UK COMPANIES ===
    {
        "name": "Revolut",
        "domain": "revolut.com",
        "industry": "FinTech",
        "hq_city": "London",
        "hq_state": "England",
        "hq_country": "UK",
        "submarket": "Canary Wharf",
        "employee_count": 8000,
        "founded_year": 2015,
        "funding_total_usd": 1800000000,
        "latest_funding_round": "Series E",
        "latest_funding_date": "2025-08-20",
        "latest_funding_amount": 800000000,
        "revenue_range": "$1B+",
        "glassdoor_rating": 3.2,
        "hybrid_percentage": 75,
        "linkedin_url": "https://linkedin.com/company/revolut",
        "crunchbase_url": "https://crunchbase.com/organization/revolut",
        "website": "https://revolut.com",
        "description": "Revolut is the global financial super app with 40M+ customers. Expanding Canary Wharf HQ as it scales banking operations post-UK banking licence.",
        "contact_name": "Francesca Sheridan",
        "contact_title": "VP Workplace & Real Estate",
        "contact_email": "f.sheridan@revolut.com",
        "contact_phone": "+44 20 7946 0107",
        "signal_tags": json.dumps(["Hiring Surge", "Banking Licence", "HQ Expansion"]),
        "ai_summary": "UK banking licence driving massive compliance and ops hiring. Adding 50K SF to Canary Wharf campus.",
        "ai_description": "Revolut's UK banking licence (granted 2025) requires substantial in-person compliance, risk, and operations teams. They're adding two floors to their Canary Wharf campus and exploring a second London site for engineering teams.",
        "hiring_trend": json.dumps([
            {"month": "Oct", "count": 45}, {"month": "Nov", "count": 55},
            {"month": "Dec", "count": 65}, {"month": "Jan", "count": 78},
            {"month": "Feb", "count": 88}, {"month": "Mar", "count": 100}
        ]),
        "evidence": json.dumps([
            {"date": "2025-07-01", "event": "Banking Licence", "description": "PRA granted full UK banking licence."},
            {"date": "2025-08-20", "event": "Funding", "description": "Raised $800M Series E at $45B valuation."},
            {"date": "2026-03-20", "event": "Real Estate", "description": "Signed HOTs for 2 additional floors at YY London, Canary Wharf."},
        ]),
    },
    {
        "name": "Monzo",
        "domain": "monzo.com",
        "industry": "FinTech",
        "hq_city": "London",
        "hq_state": "England",
        "hq_country": "UK",
        "submarket": "Finsbury Square / Moorgate",
        "employee_count": 3200,
        "founded_year": 2015,
        "funding_total_usd": 1150000000,
        "latest_funding_round": "Series H",
        "latest_funding_date": "2025-10-15",
        "latest_funding_amount": 430000000,
        "revenue_range": "$500M-$1B",
        "glassdoor_rating": 4.1,
        "hybrid_percentage": 60,
        "linkedin_url": "https://linkedin.com/company/monzo",
        "crunchbase_url": "https://crunchbase.com/organization/monzo",
        "website": "https://monzo.com",
        "description": "Monzo is the UK's leading digital bank with 9M+ customers. Profitable and expanding its Broadwalk House HQ.",
        "contact_name": "Sujata Bhatia",
        "contact_title": "COO",
        "contact_email": "s.bhatia@monzo.com",
        "contact_phone": "+44 20 7946 0108",
        "signal_tags": json.dumps(["Profitable", "HQ Upgrade", "Hiring Surge"]),
        "ai_summary": "Newly profitable challenger bank outgrowing Broadwalk House. Seeking 25K SF upgrade in Moorgate/City.",
        "ai_description": "Monzo hit profitability in 2025 and is investing heavily in business banking and lending products. Their current Broadwalk House office can't support the 500+ person hiring plan, prompting a search for a larger City of London headquarters.",
        "hiring_trend": json.dumps([
            {"month": "Oct", "count": 25}, {"month": "Nov", "count": 30},
            {"month": "Dec", "count": 35}, {"month": "Jan", "count": 42},
            {"month": "Feb", "count": 50}, {"month": "Mar", "count": 58}
        ]),
        "evidence": json.dumps([
            {"date": "2025-10-15", "event": "Funding", "description": "Raised \u00a3340M Series H, valuation \u00a34.5B."},
            {"date": "2026-01-10", "event": "Profitability", "description": "Reported first full-year profit, revenue up 90% YoY."},
            {"date": "2026-03-15", "event": "Hiring", "description": "58 London roles posted across engineering, lending, and ops."},
        ]),
    },
    {
        "name": "Darktrace",
        "domain": "darktrace.com",
        "industry": "Cybersecurity",
        "hq_city": "London",
        "hq_state": "England",
        "hq_country": "UK",
        "submarket": "Liverpool Street / Spitalfields",
        "employee_count": 2400,
        "founded_year": 2013,
        "funding_total_usd": 230000000,
        "latest_funding_round": "Private Equity",
        "latest_funding_date": "2025-04-01",
        "latest_funding_amount": 5300000000,
        "revenue_range": "$500M-$1B",
        "glassdoor_rating": 3.6,
        "hybrid_percentage": 65,
        "linkedin_url": "https://linkedin.com/company/darktrace",
        "crunchbase_url": "https://crunchbase.com/organization/darktrace",
        "website": "https://darktrace.com",
        "description": "Darktrace is a global AI cybersecurity leader. Post-Thoma Bravo acquisition, consolidating London offices into a flagship campus.",
        "contact_name": "Jill Sherwood",
        "contact_title": "VP Global Real Estate",
        "contact_email": "j.sherwood@darktrace.com",
        "contact_phone": "+44 20 7946 0109",
        "signal_tags": json.dumps(["PE Acquisition", "Office Consolidation"]),
        "ai_summary": "Post-Thoma Bravo take-private, consolidating 3 London offices into one 35K SF flagship in the City.",
        "ai_description": "Darktrace was taken private by Thoma Bravo for $5.3B. The new ownership is rationalising real estate by consolidating three small London offices into a single flagship. They're seeking 30-35K SF of premium space near Liverpool Street or the City.",
        "hiring_trend": json.dumps([
            {"month": "Oct", "count": 18}, {"month": "Nov", "count": 20},
            {"month": "Dec", "count": 22}, {"month": "Jan", "count": 25},
            {"month": "Feb", "count": 28}, {"month": "Mar", "count": 32}
        ]),
        "evidence": json.dumps([
            {"date": "2025-04-01", "event": "Acquisition", "description": "Thoma Bravo completed $5.3B take-private."},
            {"date": "2026-02-10", "event": "Consolidation", "description": "Announced plan to merge 3 London offices into one campus."},
            {"date": "2026-03-18", "event": "Real Estate", "description": "Engaged CBRE for 30-35K SF search in City of London."},
        ]),
    },
    {
        "name": "Wayve",
        "domain": "wayve.ai",
        "industry": "Autonomous Vehicles",
        "hq_city": "London",
        "hq_state": "England",
        "hq_country": "UK",
        "submarket": "King's Cross",
        "employee_count": 400,
        "founded_year": 2017,
        "funding_total_usd": 1250000000,
        "latest_funding_round": "Series C",
        "latest_funding_date": "2025-05-15",
        "latest_funding_amount": 1050000000,
        "revenue_range": "$10M-$50M",
        "glassdoor_rating": 4.2,
        "hybrid_percentage": 85,
        "linkedin_url": "https://linkedin.com/company/wayve",
        "crunchbase_url": "https://crunchbase.com/organization/wayve",
        "website": "https://wayve.ai",
        "description": "Wayve builds AI-first autonomous driving technology. Largest ever European AV funding round fuelling King's Cross expansion.",
        "contact_name": "Alex Sheridan",
        "contact_title": "Head of Operations",
        "contact_email": "a.sheridan@wayve.ai",
        "contact_phone": "+44 20 7946 0110",
        "signal_tags": json.dumps(["Mega Funding", "Hiring Surge", "Lab Space"]),
        "ai_summary": "$1B-funded AV startup tripling King's Cross team. Needs 20K SF office + simulation lab space.",
        "ai_description": "Wayve is Europe's best-funded autonomous driving company. Post-$1B Series C (SoftBank-led), they're scaling from 400 to 1000+ employees in King's Cross. They need combined office and simulation lab space, a rare requirement in central London.",
        "hiring_trend": json.dumps([
            {"month": "Oct", "count": 12}, {"month": "Nov", "count": 18},
            {"month": "Dec", "count": 25}, {"month": "Jan", "count": 35},
            {"month": "Feb", "count": 42}, {"month": "Mar", "count": 55}
        ]),
        "evidence": json.dumps([
            {"date": "2025-05-15", "event": "Funding", "description": "Raised $1.05B Series C led by SoftBank, largest European AV round."},
            {"date": "2026-02-01", "event": "Hiring", "description": "50+ ML engineer and researcher roles posted for London."},
            {"date": "2026-03-22", "event": "Lab Space", "description": "Searching for combined office + AV simulation lab near King's Cross."},
        ]),
    },
    {
        "name": "Tractable",
        "domain": "tractable.ai",
        "industry": "InsurTech / AI",
        "hq_city": "London",
        "hq_state": "England",
        "hq_country": "UK",
        "submarket": "Covent Garden / Holborn",
        "employee_count": 350,
        "founded_year": 2014,
        "funding_total_usd": 115000000,
        "latest_funding_round": "Series D",
        "latest_funding_date": "2025-09-01",
        "latest_funding_amount": 65000000,
        "revenue_range": "$50M-$100M",
        "glassdoor_rating": 4.0,
        "hybrid_percentage": 70,
        "linkedin_url": "https://linkedin.com/company/tractable",
        "crunchbase_url": "https://crunchbase.com/organization/tractable",
        "website": "https://tractable.ai",
        "description": "Tractable uses AI for visual assessment in insurance claims. Growing London HQ as it scales globally.",
        "contact_name": "Alex Dalyac",
        "contact_title": "CEO & Co-founder",
        "contact_email": "a.dalyac@tractable.ai",
        "contact_phone": "+44 20 7946 0111",
        "signal_tags": json.dumps(["Series D Funded", "Hiring Growth"]),
        "ai_summary": "AI insurtech growing London team by 40% post-Series D. Current Holborn office at 85% capacity.",
        "ai_description": "Tractable's AI visual assessment platform is being adopted by major insurers globally. Post-Series D, they're expanding their London engineering and data science teams. Current Holborn office is nearing capacity.",
        "hiring_trend": json.dumps([
            {"month": "Oct", "count": 8}, {"month": "Nov", "count": 10},
            {"month": "Dec", "count": 13}, {"month": "Jan", "count": 16},
            {"month": "Feb", "count": 20}, {"month": "Mar", "count": 24}
        ]),
        "evidence": json.dumps([
            {"date": "2025-09-01", "event": "Funding", "description": "Raised $65M Series D."},
            {"date": "2026-03-10", "event": "Hiring", "description": "24 London roles posted, mostly engineering and data science."},
        ]),
    },
    # === EUROPEAN COMPANIES WITH LONDON PRESENCE ===
    {
        "name": "Klarna",
        "domain": "klarna.com",
        "industry": "FinTech",
        "hq_city": "London",
        "hq_state": "England",
        "hq_country": "UK",
        "submarket": "Oxford Circus / Great Portland St",
        "employee_count": 5000,
        "founded_year": 2005,
        "funding_total_usd": 4500000000,
        "latest_funding_round": "Pre-IPO",
        "latest_funding_date": "2025-08-01",
        "latest_funding_amount": 800000000,
        "revenue_range": "$1B+",
        "glassdoor_rating": 3.4,
        "hybrid_percentage": 60,
        "linkedin_url": "https://linkedin.com/company/klarna",
        "crunchbase_url": "https://crunchbase.com/organization/klarna",
        "website": "https://klarna.com",
        "description": "Klarna is the global BNPL and payments leader (Stockholm HQ). Re-expanding London office post-layoffs as revenue surges.",
        "contact_name": "David Sandstrom",
        "contact_title": "Chief Marketing Officer",
        "contact_email": "d.sandstrom@klarna.com",
        "contact_phone": "+44 20 7946 0112",
        "signal_tags": json.dumps(["Pre-IPO", "Re-expansion", "Revenue Growth"]),
        "ai_summary": "Post-restructuring growth mode. Re-hiring 200+ in London ahead of 2026 IPO filing.",
        "ai_description": "After aggressive AI-driven headcount reduction in 2023-24, Klarna is now re-hiring across London in growth functions. Their Great Portland Street office has excess capacity from layoffs but they're filling it rapidly as revenue hits $2B+ and IPO approaches.",
        "hiring_trend": json.dumps([
            {"month": "Oct", "count": 15}, {"month": "Nov", "count": 22},
            {"month": "Dec", "count": 28}, {"month": "Jan", "count": 35},
            {"month": "Feb", "count": 42}, {"month": "Mar", "count": 50}
        ]),
        "evidence": json.dumps([
            {"date": "2025-08-01", "event": "Funding", "description": "Raised $800M pre-IPO round at $14.6B valuation."},
            {"date": "2026-01-20", "event": "Re-hiring", "description": "Announced 200+ new London hires in engineering and marketing."},
            {"date": "2026-03-15", "event": "IPO Prep", "description": "Filed preliminary prospectus for London Stock Exchange IPO."},
        ]),
    },
    {
        "name": "Mistral AI",
        "domain": "mistral.ai",
        "industry": "Artificial Intelligence",
        "hq_city": "London",
        "hq_state": "England",
        "hq_country": "UK",
        "submarket": "Mayfair / St James's",
        "employee_count": 700,
        "founded_year": 2023,
        "funding_total_usd": 2200000000,
        "latest_funding_round": "Series B",
        "latest_funding_date": "2025-11-15",
        "latest_funding_amount": 600000000,
        "revenue_range": "$50M-$100M",
        "glassdoor_rating": 4.4,
        "hybrid_percentage": 80,
        "linkedin_url": "https://linkedin.com/company/mistralai",
        "crunchbase_url": "https://crunchbase.com/organization/mistral-ai",
        "website": "https://mistral.ai",
        "description": "Mistral AI is the leading European LLM company (Paris HQ). Opening London as its primary English-speaking market office.",
        "contact_name": "Guillaume Lample",
        "contact_title": "VP Engineering",
        "contact_email": "g.lample@mistral.ai",
        "contact_phone": "+44 20 7946 0113",
        "signal_tags": json.dumps(["New London Office", "AI Pioneer", "Series B Funded"]),
        "ai_summary": "Europe's top AI lab opening first London office. Seeking 12K SF for 80-person research and enterprise team.",
        "ai_description": "Mistral AI is establishing its English-speaking market headquarters in London. They're building a research team to complement Paris and an enterprise sales team for UK/US clients. Looking for premium space in Mayfair or Fitzrovia that reflects their premium brand positioning.",
        "hiring_trend": json.dumps([
            {"month": "Oct", "count": 5}, {"month": "Nov", "count": 10},
            {"month": "Dec", "count": 18}, {"month": "Jan", "count": 25},
            {"month": "Feb", "count": 32}, {"month": "Mar", "count": 42}
        ]),
        "evidence": json.dumps([
            {"date": "2025-11-15", "event": "Funding", "description": "Raised \u20ac600M Series B at \u20ac6B valuation."},
            {"date": "2026-02-01", "event": "London Office", "description": "Announced London as primary English-market hub."},
            {"date": "2026-03-20", "event": "Hiring", "description": "42 London roles: ML researchers, enterprise sales, partnerships."},
        ]),
    },
    {
        "name": "N26",
        "domain": "n26.com",
        "industry": "FinTech",
        "hq_city": "London",
        "hq_state": "England",
        "hq_country": "UK",
        "submarket": "Shoreditch / Spitalfields",
        "employee_count": 1500,
        "founded_year": 2013,
        "funding_total_usd": 1700000000,
        "latest_funding_round": "Series E",
        "latest_funding_date": "2024-02-01",
        "latest_funding_amount": 100000000,
        "revenue_range": "$200M-$500M",
        "glassdoor_rating": 3.3,
        "hybrid_percentage": 55,
        "linkedin_url": "https://linkedin.com/company/n26",
        "crunchbase_url": "https://crunchbase.com/organization/n26",
        "website": "https://n26.com",
        "description": "N26 is the Berlin-based digital bank re-entering the UK market. Opening a London office for UK banking operations.",
        "contact_name": "Andrea Fichtner",
        "contact_title": "UK Country Manager",
        "contact_email": "a.fichtner@n26.com",
        "contact_phone": "+44 20 7946 0114",
        "signal_tags": json.dumps(["UK Re-entry", "Banking", "New Office"]),
        "ai_summary": "Berlin neobank re-entering UK market. Setting up 5K SF London office for 40-person regulatory and ops team.",
        "ai_description": "N26 withdrew from the UK in 2020 but is now re-entering following a new EMI licence application. They need a small London office (5K SF) for their initial regulatory, compliance, and operations team, with room to grow as they relaunch UK consumer banking.",
        "hiring_trend": json.dumps([
            {"month": "Oct", "count": 2}, {"month": "Nov", "count": 4},
            {"month": "Dec", "count": 6}, {"month": "Jan", "count": 10},
            {"month": "Feb", "count": 14}, {"month": "Mar", "count": 18}
        ]),
        "evidence": json.dumps([
            {"date": "2026-01-05", "event": "UK Re-entry", "description": "Filed EMI licence application with FCA for UK re-launch."},
            {"date": "2026-03-01", "event": "Hiring", "description": "18 London roles: compliance, risk, customer ops."},
        ]),
    },
    {
        "name": "Deliveroo",
        "domain": "deliveroo.co.uk",
        "industry": "Food Delivery / Technology",
        "hq_city": "London",
        "hq_state": "England",
        "hq_country": "UK",
        "submarket": "Cannon Street / City",
        "employee_count": 3500,
        "founded_year": 2013,
        "funding_total_usd": 1700000000,
        "latest_funding_round": "Public",
        "latest_funding_date": "2021-03-31",
        "latest_funding_amount": 0,
        "revenue_range": "$1B+",
        "glassdoor_rating": 3.5,
        "hybrid_percentage": 50,
        "linkedin_url": "https://linkedin.com/company/deliveroo",
        "crunchbase_url": "https://crunchbase.com/organization/deliveroo",
        "website": "https://deliveroo.co.uk",
        "description": "Deliveroo is the UK's leading food delivery platform. Consolidating after DoorDash acquisition approach.",
        "contact_name": "Eric French",
        "contact_title": "CFO",
        "contact_email": "e.french@deliveroo.co.uk",
        "contact_phone": "+44 20 7946 0115",
        "signal_tags": json.dumps(["Acquisition Target", "Consolidation"]),
        "ai_summary": "Post-DoorDash acquisition talks, may consolidate or expand London HQ depending on deal outcome.",
        "ai_description": "Deliveroo is in talks with DoorDash about a potential acquisition. If the deal goes through, there will be significant office consolidation or expansion as teams merge. Either way, their Cannon Street lease is up for renewal in 2027.",
        "hiring_trend": json.dumps([
            {"month": "Oct", "count": 20}, {"month": "Nov", "count": 18},
            {"month": "Dec", "count": 15}, {"month": "Jan", "count": 14},
            {"month": "Feb", "count": 16}, {"month": "Mar", "count": 18}
        ]),
        "evidence": json.dumps([
            {"date": "2026-02-15", "event": "M&A", "description": "DoorDash confirmed in advanced acquisition talks."},
            {"date": "2026-03-10", "event": "Lease Intel", "description": "Cannon Street lease expires March 2027."},
        ]),
    },
    {
        "name": "Thought Machine",
        "domain": "thoughtmachine.net",
        "industry": "Banking Technology",
        "hq_city": "London",
        "hq_state": "England",
        "hq_country": "UK",
        "submarket": "Moorgate / Finsbury Circus",
        "employee_count": 800,
        "founded_year": 2014,
        "funding_total_usd": 563000000,
        "latest_funding_round": "Series D",
        "latest_funding_date": "2025-05-01",
        "latest_funding_amount": 150000000,
        "revenue_range": "$50M-$100M",
        "glassdoor_rating": 4.0,
        "hybrid_percentage": 75,
        "linkedin_url": "https://linkedin.com/company/thoughtmachine",
        "crunchbase_url": "https://crunchbase.com/organization/thought-machine",
        "website": "https://thoughtmachine.net",
        "description": "Thought Machine builds cloud-native core banking technology. Expanding London HQ as Tier 1 banks adopt Vault platform.",
        "contact_name": "Paul Taylor",
        "contact_title": "CEO & Founder",
        "contact_email": "p.taylor@thoughtmachine.net",
        "contact_phone": "+44 20 7946 0116",
        "signal_tags": json.dumps(["Series D Funded", "Hiring Surge", "Banking Platform"]),
        "ai_summary": "Core banking platform winning Tier 1 deals. Growing London team from 500 to 800+ within 12 months.",
        "ai_description": "Thought Machine's Vault core banking platform is being adopted by major banks including JPMorgan and Lloyds. Their current Moorgate office is at capacity and they need 15K+ SF to accommodate engineering growth in London.",
        "hiring_trend": json.dumps([
            {"month": "Oct", "count": 15}, {"month": "Nov", "count": 20},
            {"month": "Dec", "count": 25}, {"month": "Jan", "count": 30},
            {"month": "Feb", "count": 38}, {"month": "Mar", "count": 45}
        ]),
        "evidence": json.dumps([
            {"date": "2025-05-01", "event": "Funding", "description": "Raised $150M Series D at $2.7B valuation."},
            {"date": "2026-01-20", "event": "Client Win", "description": "Signed Tier 1 bank deal worth $50M+ TCV."},
            {"date": "2026-03-15", "event": "Capacity", "description": "Moorgate office at 95% utilisation, touring larger spaces."},
        ]),
    },
    {
        "name": "Figma",
        "domain": "figma.com",
        "industry": "Design Software",
        "hq_city": "London",
        "hq_state": "England",
        "hq_country": "UK",
        "submarket": "Clerkenwell / Farringdon",
        "employee_count": 1500,
        "founded_year": 2012,
        "funding_total_usd": 333000000,
        "latest_funding_round": "Series E",
        "latest_funding_date": "2024-05-01",
        "latest_funding_amount": 100000000,
        "revenue_range": "$500M-$1B",
        "glassdoor_rating": 4.5,
        "hybrid_percentage": 65,
        "linkedin_url": "https://linkedin.com/company/figma",
        "crunchbase_url": "https://crunchbase.com/organization/figma",
        "website": "https://figma.com",
        "description": "Figma is the collaborative design platform. Expanding London as its European design community hub.",
        "contact_name": "Claire Butler",
        "contact_title": "VP EMEA",
        "contact_email": "c.butler@figma.com",
        "contact_phone": "+44 20 7946 0117",
        "signal_tags": json.dumps(["London Growth", "Design Leader"]),
        "ai_summary": "Design platform growing London from 40 to 100+ as European community hub. 8K SF needed in EC1.",
        "ai_description": "Figma is investing in London as its European community and enterprise sales hub. They're growing from 40 to 100+ London staff and need purpose-built space with event capacity for community gatherings and workshops.",
        "hiring_trend": json.dumps([
            {"month": "Oct", "count": 6}, {"month": "Nov", "count": 8},
            {"month": "Dec", "count": 10}, {"month": "Jan", "count": 14},
            {"month": "Feb", "count": 18}, {"month": "Mar", "count": 22}
        ]),
        "evidence": json.dumps([
            {"date": "2026-01-10", "event": "Product", "description": "Launched Figma AI driving enterprise adoption across Europe."},
            {"date": "2026-03-05", "event": "London Growth", "description": "22 London roles: sales, community, design advocacy."},
        ]),
    },
    {
        "name": "Rippling",
        "domain": "rippling.com",
        "industry": "HR Technology",
        "hq_city": "London",
        "hq_state": "England",
        "hq_country": "UK",
        "submarket": "Fitzrovia / Tottenham Court Road",
        "employee_count": 3200,
        "founded_year": 2016,
        "funding_total_usd": 1400000000,
        "latest_funding_round": "Series F",
        "latest_funding_date": "2025-11-20",
        "latest_funding_amount": 450000000,
        "revenue_range": "$200M-$500M",
        "glassdoor_rating": 3.5,
        "hybrid_percentage": 80,
        "linkedin_url": "https://linkedin.com/company/rippling",
        "crunchbase_url": "https://crunchbase.com/organization/rippling",
        "website": "https://rippling.com",
        "description": "Rippling provides unified HR, IT, and Finance software. Opening London as its first international office.",
        "contact_name": "Matt MacInnis",
        "contact_title": "VP International",
        "contact_email": "m.macinnis@rippling.com",
        "contact_phone": "+44 20 7946 0118",
        "signal_tags": json.dumps(["New London Office", "Series F Funded", "International Launch"]),
        "ai_summary": "Opening first international office in London. 35 UK roles posted, seeking 10K SF in Fitzrovia.",
        "ai_description": "Rippling is launching international expansion starting with London. They're building a 60-person UK team covering sales, engineering, and customer support. Seeking modern 10K SF office space in Fitzrovia or Soho with room to double within 18 months.",
        "hiring_trend": json.dumps([
            {"month": "Oct", "count": 3}, {"month": "Nov", "count": 8},
            {"month": "Dec", "count": 14}, {"month": "Jan", "count": 20},
            {"month": "Feb", "count": 28}, {"month": "Mar", "count": 35}
        ]),
        "evidence": json.dumps([
            {"date": "2025-11-20", "event": "Funding", "description": "Raised $450M Series F at $13.5B valuation."},
            {"date": "2026-01-15", "event": "London Office", "description": "Announced London as first international office."},
            {"date": "2026-03-10", "event": "Hiring", "description": "35 London-based roles posted across all functions."},
        ]),
    },
    {
        "name": "Anthropic",
        "domain": "anthropic.com",
        "industry": "Artificial Intelligence",
        "hq_city": "London",
        "hq_state": "England",
        "hq_country": "UK",
        "submarket": "King's Cross / Somers Town",
        "employee_count": 1500,
        "founded_year": 2021,
        "funding_total_usd": 11500000000,
        "latest_funding_round": "Series E",
        "latest_funding_date": "2025-11-01",
        "latest_funding_amount": 2000000000,
        "revenue_range": "$500M-$1B",
        "glassdoor_rating": 4.5,
        "hybrid_percentage": 75,
        "linkedin_url": "https://linkedin.com/company/anthropic",
        "crunchbase_url": "https://crunchbase.com/organization/anthropic",
        "website": "https://anthropic.com",
        "description": "Anthropic is the AI safety company behind Claude. Opening London office as first European base to attract top UK AI talent.",
        "contact_name": "Daniela Amodei",
        "contact_title": "President & Co-founder",
        "contact_email": "london@anthropic.com",
        "contact_phone": "+44 20 7946 0119",
        "signal_tags": json.dumps(["New London Office", "AI Safety Leader", "Mega Funding"]),
        "ai_summary": "AI safety leader opening first European office in London. Seeking 15K SF for 100+ research and policy team.",
        "ai_description": "Anthropic is establishing its first European presence in London, drawn by the UK AI Safety Institute and deep AI research talent pool. They need premium office space near King's Cross or Cambridge for a team of AI researchers, policy experts, and enterprise sales professionals.",
        "hiring_trend": json.dumps([
            {"month": "Oct", "count": 8}, {"month": "Nov", "count": 15},
            {"month": "Dec", "count": 22}, {"month": "Jan", "count": 30},
            {"month": "Feb", "count": 38}, {"month": "Mar", "count": 48}
        ]),
        "evidence": json.dumps([
            {"date": "2025-11-01", "event": "Funding", "description": "Raised $2B Series E at $60B valuation."},
            {"date": "2026-02-01", "event": "London Office", "description": "Announced London as first European office, citing UK AI Safety Institute."},
            {"date": "2026-03-18", "event": "Hiring", "description": "48 London roles: AI researchers, policy, enterprise sales."},
        ]),
    },
]

EXTRA_COMPANIES = [
    # === MORE US COMPANIES OPENING LONDON ===
    {
        "name": "Notion", "domain": "notion.so", "industry": "Productivity Software",
        "hq_city": "London", "hq_state": "England", "hq_country": "UK",
        "submarket": "Clerkenwell", "employee_count": 800, "founded_year": 2016,
        "funding_total_usd": 343000000, "latest_funding_round": "Series C",
        "latest_funding_date": "2024-02-01", "latest_funding_amount": 150000000,
        "revenue_range": "$200M-$500M", "glassdoor_rating": 3.9, "hybrid_percentage": 60,
        "website": "https://notion.so",
        "description": "Notion is the connected workspace combining notes, docs, wikis, and AI. Opening London office for EMEA enterprise sales.",
        "contact_name": "Camille Ricketts", "contact_title": "VP Marketing",
        "contact_email": "c.ricketts@notion.so", "contact_phone": "+44 20 7946 0120",
        "signal_tags": json.dumps(["New London Office", "Enterprise Push"]),
        "ai_summary": "Workspace platform opening London for EMEA enterprise push. 15 roles posted, seeking 5K SF in EC1.",
        "ai_description": "Notion is building its European go-to-market team in London to pursue enterprise deals with FTSE 100 companies.",
        "hiring_trend": json.dumps([{"month": "Oct", "count": 3}, {"month": "Nov", "count": 5}, {"month": "Dec", "count": 7}, {"month": "Jan", "count": 10}, {"month": "Feb", "count": 12}, {"month": "Mar", "count": 15}]),
        "evidence": json.dumps([{"date": "2026-02-01", "event": "London Office", "description": "Announced London as first European office."}, {"date": "2026-03-15", "event": "Hiring", "description": "15 London-based enterprise sales and support roles."}]),
    },
    {
        "name": "Vercel", "domain": "vercel.com", "industry": "Developer Platform",
        "hq_city": "London", "hq_state": "England", "hq_country": "UK",
        "submarket": "Shoreditch / Hackney", "employee_count": 500, "founded_year": 2015,
        "funding_total_usd": 313000000, "latest_funding_round": "Series D",
        "latest_funding_date": "2025-05-01", "latest_funding_amount": 150000000,
        "revenue_range": "$100M-$200M", "glassdoor_rating": 4.3, "hybrid_percentage": 40,
        "website": "https://vercel.com",
        "description": "Vercel is the frontend cloud platform behind Next.js. Opening London engineering hub.",
        "contact_name": "Guillermo Rauch", "contact_title": "CEO & Founder",
        "contact_email": "g.rauch@vercel.com", "contact_phone": "+44 20 7946 0121",
        "signal_tags": json.dumps(["New London Office", "Developer Tools"]),
        "ai_summary": "Next.js creators opening London engineering hub. 12 roles posted, seeking flexible 4K SF workspace.",
        "ai_description": "Vercel is tapping London's frontend engineering talent pool with a new engineering hub in Shoreditch.",
        "hiring_trend": json.dumps([{"month": "Oct", "count": 2}, {"month": "Nov", "count": 4}, {"month": "Dec", "count": 5}, {"month": "Jan", "count": 7}, {"month": "Feb", "count": 10}, {"month": "Mar", "count": 12}]),
        "evidence": json.dumps([{"date": "2026-02-15", "event": "London Hub", "description": "Announced London engineering office."}, {"date": "2026-03-10", "event": "Hiring", "description": "12 London engineering roles posted."}]),
    },
    {
        "name": "Retool", "domain": "retool.com", "industry": "Developer Tools",
        "hq_city": "London", "hq_state": "England", "hq_country": "UK",
        "submarket": "Farringdon / Clerkenwell", "employee_count": 500, "founded_year": 2017,
        "funding_total_usd": 445000000, "latest_funding_round": "Series C",
        "latest_funding_date": "2024-01-15", "latest_funding_amount": 45000000,
        "revenue_range": "$100M-$200M", "glassdoor_rating": 4.2, "hybrid_percentage": 90,
        "website": "https://retool.com",
        "description": "Retool is the fastest way to build internal tools. Famously in-office, opening London with same 5-day mandate.",
        "contact_name": "David Hsu", "contact_title": "CEO & Co-founder",
        "contact_email": "d.hsu@retool.com", "contact_phone": "+44 20 7946 0122",
        "signal_tags": json.dumps(["In-Office Mandate", "New London Office"]),
        "ai_summary": "Anti-remote dev tools company bringing 5-day in-office culture to London. 10 roles, 3K SF needed.",
        "ai_description": "Retool requires 5 days/week in-office globally. Their London office will follow the same policy, needing 3K SF in a central location with strong transport links.",
        "hiring_trend": json.dumps([{"month": "Oct", "count": 1}, {"month": "Nov", "count": 2}, {"month": "Dec", "count": 3}, {"month": "Jan", "count": 5}, {"month": "Feb", "count": 7}, {"month": "Mar", "count": 10}]),
        "evidence": json.dumps([{"date": "2026-03-01", "event": "London", "description": "10 London roles posted, all requiring 5-day in-office."}]),
    },
    # === MORE UK / LONDON NATIVES ===
    {
        "name": "Checkout.com", "domain": "checkout.com", "industry": "Payments",
        "hq_city": "London", "hq_state": "England", "hq_country": "UK",
        "submarket": "Fitzrovia / Goodge Street", "employee_count": 1700, "founded_year": 2012,
        "funding_total_usd": 1800000000, "latest_funding_round": "Series D",
        "latest_funding_date": "2022-01-01", "latest_funding_amount": 1000000000,
        "revenue_range": "$500M-$1B", "glassdoor_rating": 3.7, "hybrid_percentage": 70,
        "website": "https://checkout.com",
        "description": "Checkout.com is the cloud-based payment processing platform for global businesses. London HQ expanding.",
        "contact_name": "Guillaume Pousaz", "contact_title": "CEO & Founder",
        "contact_email": "g.pousaz@checkout.com", "contact_phone": "+44 20 7946 0123",
        "signal_tags": json.dumps(["HQ Expansion", "Payments Giant"]),
        "ai_summary": "Payments unicorn expanding Fitzrovia HQ. 45 London roles posted as enterprise pipeline grows.",
        "ai_description": "Checkout.com is expanding its Fitzrovia headquarters to accommodate growing enterprise sales and engineering teams as payment volume surges.",
        "hiring_trend": json.dumps([{"month": "Oct", "count": 20}, {"month": "Nov", "count": 25}, {"month": "Dec", "count": 28}, {"month": "Jan", "count": 32}, {"month": "Feb", "count": 38}, {"month": "Mar", "count": 45}]),
        "evidence": json.dumps([{"date": "2026-02-01", "event": "Growth", "description": "Payment volume up 60% YoY."}, {"date": "2026-03-20", "event": "Hiring", "description": "45 London roles across engineering and commercial."}]),
    },
    {
        "name": "GoCardless", "domain": "gocardless.com", "industry": "FinTech",
        "hq_city": "London", "hq_state": "England", "hq_country": "UK",
        "submarket": "Sutton Yard / Clerkenwell", "employee_count": 900, "founded_year": 2011,
        "funding_total_usd": 530000000, "latest_funding_round": "Series G",
        "latest_funding_date": "2025-06-01", "latest_funding_amount": 100000000,
        "revenue_range": "$100M-$200M", "glassdoor_rating": 4.0, "hybrid_percentage": 60,
        "website": "https://gocardless.com",
        "description": "GoCardless is the global leader in direct debit payments. Growing London HQ post-profitability.",
        "contact_name": "Hiroki Takeuchi", "contact_title": "CEO & Co-founder",
        "contact_email": "h.takeuchi@gocardless.com", "contact_phone": "+44 20 7946 0124",
        "signal_tags": json.dumps(["Profitable", "HQ Growth"]),
        "ai_summary": "Direct debit platform hitting profitability. Growing London team and considering HQ upgrade.",
        "ai_description": "GoCardless has reached profitability and is investing in growth. Their Sutton Yard office is approaching capacity as engineering and sales teams expand.",
        "hiring_trend": json.dumps([{"month": "Oct", "count": 10}, {"month": "Nov", "count": 12}, {"month": "Dec", "count": 14}, {"month": "Jan", "count": 18}, {"month": "Feb", "count": 22}, {"month": "Mar", "count": 28}]),
        "evidence": json.dumps([{"date": "2025-06-01", "event": "Funding", "description": "Raised $100M Series G."}, {"date": "2026-03-10", "event": "Hiring", "description": "28 London roles, primarily engineering."}]),
    },
    {
        "name": "Improbable", "domain": "improbable.io", "industry": "Metaverse / Defence",
        "hq_city": "London", "hq_state": "England", "hq_country": "UK",
        "submarket": "Spitalfields / Brick Lane", "employee_count": 700, "founded_year": 2012,
        "funding_total_usd": 600000000, "latest_funding_round": "Series B",
        "latest_funding_date": "2025-03-01", "latest_funding_amount": 150000000,
        "revenue_range": "$50M-$100M", "glassdoor_rating": 3.4, "hybrid_percentage": 65,
        "website": "https://improbable.io",
        "description": "Improbable builds synthetic environment technology for defence and gaming. Pivoting to defence driving London hiring.",
        "contact_name": "Herman Sheridan", "contact_title": "CEO & Co-founder",
        "contact_email": "h.sheridan@improbable.io", "contact_phone": "+44 20 7946 0125",
        "signal_tags": json.dumps(["Defence Pivot", "Hiring Surge"]),
        "ai_summary": "Defence simulation company hiring aggressively for MOD contracts. 22 cleared roles in London.",
        "ai_description": "Improbable's pivot from gaming to defence simulation is driving significant hiring in London. They need SC-cleared staff and appropriate office space.",
        "hiring_trend": json.dumps([{"month": "Oct", "count": 5}, {"month": "Nov", "count": 8}, {"month": "Dec", "count": 12}, {"month": "Jan", "count": 15}, {"month": "Feb", "count": 18}, {"month": "Mar", "count": 22}]),
        "evidence": json.dumps([{"date": "2025-03-01", "event": "Funding", "description": "Raised $150M for defence division."}, {"date": "2026-03-05", "event": "Hiring", "description": "22 London roles requiring security clearance."}]),
    },
    {
        "name": "Cazoo", "domain": "cazoo.co.uk", "industry": "Automotive / E-commerce",
        "hq_city": "London", "hq_state": "England", "hq_country": "UK",
        "submarket": "Euston / Camden", "employee_count": 400, "founded_year": 2018,
        "funding_total_usd": 2000000000, "latest_funding_round": "Restructured",
        "latest_funding_date": "2025-01-01", "latest_funding_amount": 0,
        "revenue_range": "$200M-$500M", "glassdoor_rating": 2.8, "hybrid_percentage": 40,
        "website": "https://cazoo.co.uk",
        "description": "Cazoo is the online used car platform. Post-restructuring, downsizing London office significantly.",
        "contact_name": "Paul Sheridan", "contact_title": "CFO",
        "contact_email": "p.sheridan@cazoo.co.uk", "contact_phone": "+44 20 7946 0126",
        "signal_tags": json.dumps(["Downsizing", "Sublease Opportunity"]),
        "ai_summary": "Post-restructuring, subleasing 15K SF of Camden office. Prime sublease opportunity for brokers.",
        "ai_description": "Cazoo has dramatically reduced headcount and is looking to sublease a significant portion of its Camden office. This represents an opportunity for tenants seeking sub-market-rate space in NW1.",
        "hiring_trend": json.dumps([{"month": "Oct", "count": 15}, {"month": "Nov", "count": 12}, {"month": "Dec", "count": 8}, {"month": "Jan", "count": 6}, {"month": "Feb", "count": 4}, {"month": "Mar", "count": 3}]),
        "evidence": json.dumps([{"date": "2025-01-01", "event": "Restructuring", "description": "Completed debt restructuring and IPO delisting."}, {"date": "2026-03-01", "event": "Sublease", "description": "15K SF listed for sublease via Savills."}]),
    },
    {
        "name": "Zopa", "domain": "zopa.com", "industry": "FinTech / Banking",
        "hq_city": "London", "hq_state": "England", "hq_country": "UK",
        "submarket": "Southwark / Borough", "employee_count": 600, "founded_year": 2005,
        "funding_total_usd": 780000000, "latest_funding_round": "Series F",
        "latest_funding_date": "2025-07-01", "latest_funding_amount": 100000000,
        "revenue_range": "$100M-$200M", "glassdoor_rating": 4.1, "hybrid_percentage": 65,
        "website": "https://zopa.com",
        "description": "Zopa is the UK digital bank born from peer-to-peer lending. Growing Southwark HQ as deposits surge.",
        "contact_name": "Jaidev Sheridan", "contact_title": "CEO",
        "contact_email": "j.sheridan@zopa.com", "contact_phone": "+44 20 7946 0127",
        "signal_tags": json.dumps(["Banking Growth", "Series F Funded"]),
        "ai_summary": "Digital bank growing deposits and lending. Expanding Southwark office by 30% for 80 new hires.",
        "ai_description": "Zopa's deposit base has tripled and they need more compliance, risk, and engineering staff in London.",
        "hiring_trend": json.dumps([{"month": "Oct", "count": 8}, {"month": "Nov", "count": 10}, {"month": "Dec", "count": 13}, {"month": "Jan", "count": 16}, {"month": "Feb", "count": 20}, {"month": "Mar", "count": 25}]),
        "evidence": json.dumps([{"date": "2025-07-01", "event": "Funding", "description": "Raised $100M Series F."}, {"date": "2026-03-15", "event": "Hiring", "description": "25 London roles across risk, engineering, and ops."}]),
    },
    {
        "name": "Paddle", "domain": "paddle.com", "industry": "Payments / SaaS",
        "hq_city": "London", "hq_state": "England", "hq_country": "UK",
        "submarket": "Holborn / Chancery Lane", "employee_count": 350, "founded_year": 2012,
        "funding_total_usd": 293000000, "latest_funding_round": "Series D",
        "latest_funding_date": "2025-04-01", "latest_funding_amount": 68000000,
        "revenue_range": "$50M-$100M", "glassdoor_rating": 4.3, "hybrid_percentage": 70,
        "website": "https://paddle.com",
        "description": "Paddle is the revenue delivery platform for SaaS companies, handling payments, tax, and subscriptions.",
        "contact_name": "Christian Sheridan", "contact_title": "CEO & Co-founder",
        "contact_email": "c.sheridan@paddle.com", "contact_phone": "+44 20 7946 0128",
        "signal_tags": json.dumps(["Series D Funded", "Moderate Growth"]),
        "ai_summary": "SaaS payments platform growing steadily. 18 London roles, current Holborn office has room.",
        "ai_description": "Paddle is growing its London team moderately post-Series D. Current office has some expansion room but they may need an upgrade in 12-18 months.",
        "hiring_trend": json.dumps([{"month": "Oct", "count": 6}, {"month": "Nov", "count": 8}, {"month": "Dec", "count": 10}, {"month": "Jan", "count": 12}, {"month": "Feb", "count": 15}, {"month": "Mar", "count": 18}]),
        "evidence": json.dumps([{"date": "2025-04-01", "event": "Funding", "description": "Raised $68M Series D."}, {"date": "2026-03-10", "event": "Hiring", "description": "18 London roles posted."}]),
    },
    # === EUROPEAN COMPANIES OPENING / EXPANDING LONDON ===
    {
        "name": "BioNTech", "domain": "biontech.com", "industry": "Biotech / Pharma",
        "hq_city": "London", "hq_state": "England", "hq_country": "UK",
        "submarket": "Cambridge / King's Cross",
        "employee_count": 5900, "founded_year": 2008,
        "funding_total_usd": 3200000000, "latest_funding_round": "Public",
        "latest_funding_date": "2020-10-01", "latest_funding_amount": 0,
        "revenue_range": "$1B+", "glassdoor_rating": 3.9, "hybrid_percentage": 25,
        "website": "https://biontech.com",
        "description": "BioNTech is the German biotech behind the Pfizer COVID vaccine. Opening London R&D and commercial office.",
        "contact_name": "Prof. Ugur Sahin", "contact_title": "CEO & Co-founder",
        "contact_email": "london@biontech.com", "contact_phone": "+44 20 7946 0129",
        "signal_tags": json.dumps(["New London Office", "Lab Space", "Biotech"]),
        "ai_summary": "mRNA pioneer opening London office for cancer therapy R&D. Needs 10K SF office + lab space.",
        "ai_description": "BioNTech is establishing a London presence for its oncology pipeline, combining a research lab with commercial offices near King's Cross or in the Cambridge corridor.",
        "hiring_trend": json.dumps([{"month": "Oct", "count": 4}, {"month": "Nov", "count": 7}, {"month": "Dec", "count": 10}, {"month": "Jan", "count": 14}, {"month": "Feb", "count": 18}, {"month": "Mar", "count": 22}]),
        "evidence": json.dumps([{"date": "2026-01-15", "event": "UK Entry", "description": "Announced London R&D centre for oncology."}, {"date": "2026-03-20", "event": "Hiring", "description": "22 UK roles: scientists, lab managers, regulatory."}]),
    },
    {
        "name": "Personio", "domain": "personio.com", "industry": "HR Technology",
        "hq_city": "London", "hq_state": "England", "hq_country": "UK",
        "submarket": "Tower Bridge / Bermondsey", "employee_count": 2000, "founded_year": 2015,
        "funding_total_usd": 740000000, "latest_funding_round": "Series E",
        "latest_funding_date": "2025-01-01", "latest_funding_amount": 200000000,
        "revenue_range": "$200M-$500M", "glassdoor_rating": 3.8, "hybrid_percentage": 70,
        "website": "https://personio.com",
        "description": "Personio is the Munich-based HR platform for SMEs. Expanding London as its UK/Ireland hub.",
        "contact_name": "Hanno Renner", "contact_title": "CEO & Co-founder",
        "contact_email": "h.renner@personio.com", "contact_phone": "+44 20 7946 0130",
        "signal_tags": json.dumps(["London Expansion", "Series E Funded"]),
        "ai_summary": "German HR unicorn doubling London team. Growing from 80 to 160 staff, needs larger office near Tower Bridge.",
        "ai_description": "Personio is doubling its London team to serve the UK SME market. Current Tower Bridge space is at capacity.",
        "hiring_trend": json.dumps([{"month": "Oct", "count": 10}, {"month": "Nov", "count": 14}, {"month": "Dec", "count": 18}, {"month": "Jan", "count": 22}, {"month": "Feb", "count": 28}, {"month": "Mar", "count": 35}]),
        "evidence": json.dumps([{"date": "2025-01-01", "event": "Funding", "description": "Raised $200M Series E at $8.5B valuation."}, {"date": "2026-03-15", "event": "London Growth", "description": "35 London roles posted, doubling UK team size."}]),
    },
    {
        "name": "Celonis", "domain": "celonis.com", "industry": "Process Mining",
        "hq_city": "London", "hq_state": "England", "hq_country": "UK",
        "submarket": "St Paul's / City", "employee_count": 3500, "founded_year": 2011,
        "funding_total_usd": 1400000000, "latest_funding_round": "Series D",
        "latest_funding_date": "2025-06-01", "latest_funding_amount": 400000000,
        "revenue_range": "$500M-$1B", "glassdoor_rating": 4.1, "hybrid_percentage": 65,
        "website": "https://celonis.com",
        "description": "Celonis is the Munich-based process mining platform. Making London its English-speaking commercial hub.",
        "contact_name": "Alexander Rinke", "contact_title": "CEO & Co-founder",
        "contact_email": "a.rinke@celonis.com", "contact_phone": "+44 20 7946 0131",
        "signal_tags": json.dumps(["London Hub", "Series D Funded", "Enterprise"]),
        "ai_summary": "Process mining leader making London its English-speaking hub. 30 roles, seeking 12K SF near St Paul's.",
        "ai_description": "Celonis is centralising its UK, US, and APAC sales leadership in London. They need a premium office near the City for client-facing meetings.",
        "hiring_trend": json.dumps([{"month": "Oct", "count": 12}, {"month": "Nov", "count": 15}, {"month": "Dec", "count": 18}, {"month": "Jan", "count": 22}, {"month": "Feb", "count": 26}, {"month": "Mar", "count": 30}]),
        "evidence": json.dumps([{"date": "2025-06-01", "event": "Funding", "description": "Raised $400M Series D at $13B valuation."}, {"date": "2026-03-10", "event": "London Hub", "description": "30 London roles posted, designating London as commercial HQ."}]),
    },
    {
        "name": "Bolt", "domain": "bolt.eu", "industry": "Mobility / Delivery",
        "hq_city": "London", "hq_state": "England", "hq_country": "UK",
        "submarket": "Shoreditch", "employee_count": 5000, "founded_year": 2013,
        "funding_total_usd": 1400000000, "latest_funding_round": "Series F",
        "latest_funding_date": "2025-03-01", "latest_funding_amount": 200000000,
        "revenue_range": "$500M-$1B", "glassdoor_rating": 3.6, "hybrid_percentage": 60,
        "website": "https://bolt.eu",
        "description": "Bolt is the Estonian ride-hailing and delivery super app. Expanding London operations as UK market grows.",
        "contact_name": "Markus Villig", "contact_title": "CEO & Founder",
        "contact_email": "m.villig@bolt.eu", "contact_phone": "+44 20 7946 0132",
        "signal_tags": json.dumps(["UK Expansion", "Series F Funded"]),
        "ai_summary": "Estonian ride-hailing app growing London ops team. 20 roles posted as UK revenue doubles.",
        "ai_description": "Bolt's UK operations are their fastest-growing market. They need larger London space for operations, driver support, and engineering teams.",
        "hiring_trend": json.dumps([{"month": "Oct", "count": 8}, {"month": "Nov", "count": 10}, {"month": "Dec", "count": 12}, {"month": "Jan", "count": 15}, {"month": "Feb", "count": 18}, {"month": "Mar", "count": 20}]),
        "evidence": json.dumps([{"date": "2025-03-01", "event": "Funding", "description": "Raised $200M Series F."}, {"date": "2026-03-08", "event": "UK Growth", "description": "UK revenue doubled YoY, 20 London roles posted."}]),
    },
    {
        "name": "SumUp", "domain": "sumup.com", "industry": "Payments / FinTech",
        "hq_city": "London", "hq_state": "England", "hq_country": "UK",
        "submarket": "London Bridge", "employee_count": 3000, "founded_year": 2012,
        "funding_total_usd": 1500000000, "latest_funding_round": "Series F",
        "latest_funding_date": "2025-09-01", "latest_funding_amount": 300000000,
        "revenue_range": "$500M-$1B", "glassdoor_rating": 3.5, "hybrid_percentage": 55,
        "website": "https://sumup.com",
        "description": "SumUp is the Berlin/London-based payments platform for small businesses. Consolidating UK ops near London Bridge.",
        "contact_name": "Marc-Alexander Christ", "contact_title": "Co-founder",
        "contact_email": "m.christ@sumup.com", "contact_phone": "+44 20 7946 0133",
        "signal_tags": json.dumps(["Office Consolidation", "Series F Funded"]),
        "ai_summary": "Payments platform consolidating two London offices into one 20K SF space near London Bridge.",
        "ai_description": "SumUp is merging its Southwark and Bermondsey offices into a single London Bridge location to improve collaboration.",
        "hiring_trend": json.dumps([{"month": "Oct", "count": 12}, {"month": "Nov", "count": 14}, {"month": "Dec", "count": 16}, {"month": "Jan", "count": 18}, {"month": "Feb", "count": 20}, {"month": "Mar", "count": 22}]),
        "evidence": json.dumps([{"date": "2025-09-01", "event": "Funding", "description": "Raised $300M Series F."}, {"date": "2026-03-01", "event": "Consolidation", "description": "Merging two London offices into one 20K SF space."}]),
    },
    {
        "name": "Wise", "domain": "wise.com", "industry": "FinTech / FX",
        "hq_city": "London", "hq_state": "England", "hq_country": "UK",
        "submarket": "Shoreditch / Tea Building", "employee_count": 5500, "founded_year": 2011,
        "funding_total_usd": 1000000000, "latest_funding_round": "Public",
        "latest_funding_date": "2021-07-07", "latest_funding_amount": 0,
        "revenue_range": "$1B+", "glassdoor_rating": 4.0, "hybrid_percentage": 60,
        "website": "https://wise.com",
        "description": "Wise (formerly TransferWise) is the global money transfer platform. Expanding Shoreditch HQ campus.",
        "contact_name": "Kristo Kaarmann", "contact_title": "CEO & Co-founder",
        "contact_email": "k.kaarmann@wise.com", "contact_phone": "+44 20 7946 0134",
        "signal_tags": json.dumps(["HQ Campus Expansion", "Revenue Growth"]),
        "ai_summary": "FX giant expanding Shoreditch campus. Adding 15K SF as customer base grows to 16M+ globally.",
        "ai_description": "Wise is expanding its iconic Shoreditch campus to support growth in its Wise Platform B2B business and new product lines.",
        "hiring_trend": json.dumps([{"month": "Oct", "count": 22}, {"month": "Nov", "count": 25}, {"month": "Dec", "count": 28}, {"month": "Jan", "count": 32}, {"month": "Feb", "count": 36}, {"month": "Mar", "count": 40}]),
        "evidence": json.dumps([{"date": "2026-01-20", "event": "Revenue", "description": "Q3 revenue up 25% YoY to \u00a3350M."}, {"date": "2026-03-15", "event": "Real Estate", "description": "Signed for additional 15K SF adjacent to Tea Building campus."}]),
    },
    {
        "name": "OakNorth", "domain": "oaknorth.com", "industry": "Banking / FinTech",
        "hq_city": "London", "hq_state": "England", "hq_country": "UK",
        "submarket": "Fitzrovia / Portland Place", "employee_count": 500, "founded_year": 2015,
        "funding_total_usd": 1000000000, "latest_funding_round": "Series C",
        "latest_funding_date": "2025-04-01", "latest_funding_amount": 200000000,
        "revenue_range": "$100M-$200M", "glassdoor_rating": 3.9, "hybrid_percentage": 70,
        "website": "https://oaknorth.com",
        "description": "OakNorth is the UK commercial lending bank and platform. Expanding Fitzrovia HQ as lending volumes surge.",
        "contact_name": "Rishi Khosla", "contact_title": "CEO & Co-founder",
        "contact_email": "r.khosla@oaknorth.com", "contact_phone": "+44 20 7946 0135",
        "signal_tags": json.dumps(["Series C Funded", "Banking Growth"]),
        "ai_summary": "Commercial lending bank growing credit team. 20 roles in London, expanding current Fitzrovia office.",
        "ai_description": "OakNorth's lending volumes are growing rapidly and they need more credit analysts and relationship managers in London.",
        "hiring_trend": json.dumps([{"month": "Oct", "count": 8}, {"month": "Nov", "count": 10}, {"month": "Dec", "count": 12}, {"month": "Jan", "count": 14}, {"month": "Feb", "count": 17}, {"month": "Mar", "count": 20}]),
        "evidence": json.dumps([{"date": "2025-04-01", "event": "Funding", "description": "Raised $200M Series C."}, {"date": "2026-03-12", "event": "Hiring", "description": "20 London roles: credit, risk, engineering."}]),
    },
    {
        "name": "Beamery", "domain": "beamery.com", "industry": "HR Tech / Talent",
        "hq_city": "London", "hq_state": "England", "hq_country": "UK",
        "submarket": "Aldgate / Whitechapel", "employee_count": 400, "founded_year": 2014,
        "funding_total_usd": 223000000, "latest_funding_round": "Series C",
        "latest_funding_date": "2025-08-01", "latest_funding_amount": 50000000,
        "revenue_range": "$50M-$100M", "glassdoor_rating": 3.8, "hybrid_percentage": 65,
        "website": "https://beamery.com",
        "description": "Beamery is the talent lifecycle management platform for enterprises. Growing London HQ post-Series C.",
        "contact_name": "Abakar Saidov", "contact_title": "CEO & Co-founder",
        "contact_email": "a.saidov@beamery.com", "contact_phone": "+44 20 7946 0136",
        "signal_tags": json.dumps(["Series C Funded", "Moderate Growth"]),
        "ai_summary": "Talent platform growing steadily post-Series C. 15 London roles, Aldgate office has expansion room.",
        "ai_description": "Beamery is growing its London engineering and sales teams. Current Aldgate office can absorb near-term growth.",
        "hiring_trend": json.dumps([{"month": "Oct", "count": 5}, {"month": "Nov", "count": 6}, {"month": "Dec", "count": 8}, {"month": "Jan", "count": 10}, {"month": "Feb", "count": 12}, {"month": "Mar", "count": 15}]),
        "evidence": json.dumps([{"date": "2025-08-01", "event": "Funding", "description": "Raised $50M Series C."}, {"date": "2026-03-10", "event": "Hiring", "description": "15 London roles posted."}]),
    },
    {
        "name": "xAI", "domain": "x.ai", "industry": "Artificial Intelligence",
        "hq_city": "London", "hq_state": "England", "hq_country": "UK",
        "submarket": "Mayfair / Piccadilly", "employee_count": 500, "founded_year": 2023,
        "funding_total_usd": 12000000000, "latest_funding_round": "Series C",
        "latest_funding_date": "2025-12-15", "latest_funding_amount": 6000000000,
        "revenue_range": "$100M-$200M", "glassdoor_rating": 3.8, "hybrid_percentage": 80,
        "website": "https://x.ai",
        "description": "xAI is Elon Musk's AI company building Grok. Opening London research office to tap DeepMind alumni.",
        "contact_name": "Igor Babuschkin", "contact_title": "VP Research",
        "contact_email": "i.babuschkin@x.ai", "contact_phone": "+44 20 7946 0137",
        "signal_tags": json.dumps(["New London Office", "Mega Funding", "AI Research"]),
        "ai_summary": "Musk's AI lab opening London office targeting DeepMind and academia talent. 25 research roles posted.",
        "ai_description": "xAI is establishing a London research lab to compete with DeepMind for UK AI talent. They're offering significantly above-market compensation and seeking premium Mayfair or King's Cross office space.",
        "hiring_trend": json.dumps([{"month": "Oct", "count": 5}, {"month": "Nov", "count": 8}, {"month": "Dec", "count": 12}, {"month": "Jan", "count": 16}, {"month": "Feb", "count": 20}, {"month": "Mar", "count": 25}]),
        "evidence": json.dumps([{"date": "2025-12-15", "event": "Funding", "description": "Raised $6B Series C at $40B valuation."}, {"date": "2026-02-15", "event": "London Lab", "description": "Announced London AI research lab."}, {"date": "2026-03-20", "event": "Hiring", "description": "25 London ML research roles, offering 2x market rate."}]),
    },
    {
        "name": "Pleo", "domain": "pleo.io", "industry": "FinTech / Expense",
        "hq_city": "London", "hq_state": "England", "hq_country": "UK",
        "submarket": "Old Street / Angel", "employee_count": 900, "founded_year": 2015,
        "funding_total_usd": 630000000, "latest_funding_round": "Series C",
        "latest_funding_date": "2025-05-01", "latest_funding_amount": 200000000,
        "revenue_range": "$100M-$200M", "glassdoor_rating": 4.2, "hybrid_percentage": 60,
        "website": "https://pleo.io",
        "description": "Pleo is the Copenhagen-based smart company card platform. London is its largest market and expanding fast.",
        "contact_name": "Jeppe Rindom", "contact_title": "CEO & Co-founder",
        "contact_email": "j.rindom@pleo.io", "contact_phone": "+44 20 7946 0138",
        "signal_tags": json.dumps(["London Expansion", "Series C Funded"]),
        "ai_summary": "Danish expense platform growing London from 60 to 120 as UK becomes largest market. 25 roles posted.",
        "ai_description": "Pleo's UK market has overtaken Denmark as its largest. They're doubling the London team and need to move from their current Old Street flex space to dedicated office.",
        "hiring_trend": json.dumps([{"month": "Oct", "count": 8}, {"month": "Nov", "count": 12}, {"month": "Dec", "count": 15}, {"month": "Jan", "count": 18}, {"month": "Feb", "count": 22}, {"month": "Mar", "count": 25}]),
        "evidence": json.dumps([{"date": "2025-05-01", "event": "Funding", "description": "Raised $200M Series C."}, {"date": "2026-03-10", "event": "London Growth", "description": "Doubling London team, 25 roles posted."}]),
    },
]

DEMO_COMPANIES.extend(EXTRA_COMPANIES)

JOB_TITLES = [
    "Software Engineer", "Senior Software Engineer", "Staff Engineer",
    "Product Manager", "Senior Product Manager", "Engineering Manager",
    "Data Scientist", "ML Engineer", "DevOps Engineer", "SRE",
    "Account Executive", "Sales Development Rep", "Solutions Architect",
    "UX Designer", "Frontend Engineer", "Backend Engineer",
    "Security Engineer", "Infrastructure Engineer", "Technical Program Manager",
    "Compliance Officer", "Risk Analyst", "Regulatory Affairs Manager",
    "Head of UK Operations", "Country Manager", "VP EMEA Sales",
]

HYBRID_PHRASES = [
    "Hybrid (3 days in office)",
    "Hybrid - London Office",
    "In-Office / Hybrid",
    "On-site, flexible remote Fridays",
    "Hybrid (Tues-Thurs in office)",
    "London HQ - Hybrid 4 days",
]


def seed_database():
    """Seed the database with London/Europe-focused demo data."""
    init_db()

    for company in DEMO_COMPANIES:
        upsert_company(company)

    all_jobs = []
    for company in DEMO_COMPANIES:
        trend = json.loads(company.get("hiring_trend", "[]"))
        latest_count = trend[-1]["count"] if trend else 20
        num_jobs = latest_count + random.randint(-5, 10)
        num_jobs = max(5, num_jobs)

        for _ in range(num_jobs):
            days_ago = random.randint(0, 90)
            date_posted = (datetime.now() - timedelta(days=days_ago)).strftime("%Y-%m-%d")
            is_hybrid = random.random() < (company.get("hybrid_percentage", 50) / 100)
            title = random.choice(JOB_TITLES)
            location = f"{company['hq_city']}, {company.get('hq_country', 'UK')}"

            if is_hybrid:
                job_type = random.choice(HYBRID_PHRASES)
            else:
                job_type = random.choice(["Remote", "On-site", "Full-time"])

            all_jobs.append({
                "company_name": company["name"],
                "company_domain": company["domain"],
                "title": title,
                "location": location,
                "job_type": job_type,
                "date_posted": date_posted,
                "source": random.choice(["linkedin", "indeed"]),
                "is_hybrid": 1 if is_hybrid else 0,
                "is_office": 1 if not is_hybrid and "Remote" not in job_type else 0,
                "raw_data": "{}",
            })

    bulk_insert_jobs(all_jobs)

    conn = get_db()
    for company in DEMO_COMPANIES:
        count = conn.execute(
            "SELECT COUNT(*) FROM job_listings WHERE company_name = ?",
            (company["name"],)
        ).fetchone()[0]
        conn.execute(
            "UPDATE companies SET job_count_90d = ? WHERE name = ?",
            (count, company["name"])
        )
    conn.commit()
    conn.close()

    scored = score_all_companies()
    print(f"Seeded {len(DEMO_COMPANIES)} companies, {len(all_jobs)} job listings, scored {scored} companies.")


if __name__ == "__main__":
    seed_database()
